# Generated by Django 6.1 on 2026-08-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='evidence',
            field=models.TextField(blank=True),
        ),
    ]
